In [1]:
import torch

D:\anaconda\envs\paper\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# 数组的建立
x = torch.Tensor([1,2,3,4])

In [4]:
x

tensor([1., 2., 3., 4.])

In [12]:
print(x.size())
print(x.dim())
print(x.numpy())

torch.Size([4])
1
[1. 2. 3. 4.]


In [14]:
# 矩阵的建立
x_1 = torch.unsqueeze(x,dim=0)
x_1

tensor([[1., 2., 3., 4.]])

In [15]:
print(x_1.size())
print(x_1.dim())
print(x_1.numpy())

torch.Size([1, 4])
2
[[1. 2. 3. 4.]]


In [16]:
x_2 = torch.unsqueeze(x,dim=1)
x_2
print(x_2.size())
print(x_2.dim())
print(x_2.numpy())

torch.Size([4, 1])
2
[[1.]
 [2.]
 [3.]
 [4.]]


In [17]:
# 逆向列扩展
x_3 = torch.unsqueeze(x,dim=-1)
x_3
print(x_3.size())
print(x_3.dim())
print(x_3.numpy())

torch.Size([4, 1])
2
[[1.]
 [2.]
 [3.]
 [4.]]


In [18]:
p=torch.Tensor([[[1,1,1],[2,2,2]],
               [[3,3,3],[4,4,4]]])
p

tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[3., 3., 3.],
         [4., 4., 4.]]])

In [20]:
p.size()
# 表示两行三列的数据有两个

torch.Size([2, 2, 3])

In [22]:
p.sum(0)

tensor([[4., 4., 4.],
        [6., 6., 6.]])

In [23]:
p.sum(1)

tensor([[3., 3., 3.],
        [7., 7., 7.]])

In [24]:
p.sum(2)

tensor([[ 3.,  6.],
        [ 9., 12.]])